spring.application.name=demo

#Database
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=123

#Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
#SQL log
spring.jpa.show-sql=true
logging.level.root=INFO

logging.level.org.hibernate=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG

logging.level.com.example.demo.Service=TRACE

logging.file.name=logs/patient_web_service.log

logging.logback.rollingpolicy.max-file-size=2MB

logging.logback.rollingpolicy.file-name-pattern=${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz

logging.logback.rollingpolicy.max-history=7

logging.logback.rollingpolicy.total-size-cap=50MB


server.port=5050

